version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "${server.PORT_CHRISTEST}:${server.PORT_CHRISTEST}"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${server.PORT_CHRISTEST}/"]
      interval: 30s
      # timeout: 3s
      retries: 3
      start_period: 5s

