version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    environment:
      - NODE_ENV=production
    ports:
      - ${server_PORT_CHRISTEST:-3000}:${server_PORT_CHRISTEST:-3000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${server_PORT_CHRISTEST:-3000}/"]
      interval: 30s
      # timeout: 3s
      retries: 3
      start_period: 5s

